language: csharp
sudo: required
dist: bionic
mono: none
dotnet: 5.0.17

install:
  - export DOTNET_CLI_TELEMETRY_OPTOUT=1
  - export DOTNET_SKIP_FIRST_TIME_EXPERIENCE=1

before_script:
  - chmod a+x ./build.sh

script:
  - ./build.sh
